-- Create storage bucket for backdoor screenshots
INSERT INTO storage.buckets (id, name, public)
VALUES ('backdoor-screenshots', 'backdoor-screenshots', false)
ON CONFLICT (id) DO NOTHING;

-- RLS policies for backdoor-screenshots bucket
-- Admins can upload
CREATE POLICY "Admins can upload backdoor screenshots"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'backdoor-screenshots' 
  AND EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Admins can view/update/delete
CREATE POLICY "Admins can manage backdoor screenshots"
ON storage.objects FOR ALL
USING (
  bucket_id = 'backdoor-screenshots' 
  AND EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Users can view their own screenshots (via signed URLs generated by admin)
-- Note: Signed URLs bypass RLS, so no SELECT policy needed for users